services:
  db-mongo:
    image: mongo:6.0.6

    environment:
      MONGO_INITDB_ROOT_USERNAME: nguyenmaianh
      MONGO_INITDB_ROOT_PASSWORD: maianh20

    ports:
      - 27017:27017

    volumes:
      - mongodb:/data/db

    expose:
      - 27017
  be_nest:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://nguyenmaianh041103:maianh20@cluster0.eeieobb.mongodb.net/

    ports:
      - 8080:8080

    expose:
      - 8080
    
volumes:
  mongodb:
      
